In [3]:
import numpy as np
from sklearn import preprocessing

In [2]:
X = np.array([[1., -1., 2.],
            [2., 0., 0.],
            [0., 1., -1.]])

In [5]:
# Method 1 - scaling only for single dataset. Thus, scales differently for both training and testing.
X_scaled = preprocessing.scale(X)

In [7]:
X_scaled.mean(axis = 0)

array([0., 0., 0.])

In [8]:
X_scaled.std(axis = 0)

array([1., 1., 1.])

In [9]:
# Method 2 - scaling for different datasets with same parameters by storing them.
# parameters stored
scaler = preprocessing.StandardScaler()
scaler.fit(X) # performs the scaling

# applies the stored parameters
scaler.transform(X)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [10]:
X_test = [[1, 1, 0]]

scaler.transform(X_test)

array([[ 0.        ,  1.22474487, -0.26726124]])

In [14]:
data = [[0, 3], 
       [9, 4], 
       [2, 7],
       [1, 1]]

scaler.fit(data)

first = scaler.transform(data)

second = scaler.transform([[2, 13],
                          [1, 4],
                          [10, 7],
                          [1, 9]])

print(first.sum())
print(second.sum())

0.0
8.879529301279849
