In [1]:
import numpy as np

In [3]:
# AND operation
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0, 0, 0, 1]]).T

In [5]:
X.shape, Y.shape

((4, 2), (4, 1))

In [6]:
# sigmoid function
def sig(z):
    return 1 / (1 + np.exp(-z))

In [ ]:
# sigmoid function derivation
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [22]:
# considering weights and bias b/w -1 and 1
# no hidden layer weights
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1

In [23]:
weights, bias

(array([[-0.36864155],
        [-0.0627267 ]]),
 array([-0.02056216]))

In [24]:
# Forward propogation without any hidden layer
output0 = X # output of input layer
output = sig(np.dot(output0, weights) + bias) # output of output layer

output

array([[0.49485964],
       [0.47918981],
       [0.40390901],
       [0.38890189]])

In [30]:
# Hidden layer weights and biases
wh = 2 * np.random.random((2, 2)) - 1
bh = 2 * np.random.random((1, 2)) - 1

# output layer weights and biases
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1, 1)) - 1

In [31]:
# Forward propogation with hidden layer
output0 = X
output_hidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(output_hidden, wo) + bo)

output

array([[0.63158892],
       [0.6353287 ],
       [0.64365605],
       [0.64720836]])