In [1]:
import numpy as np

In [2]:
# AND operation
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0, 0, 0, 1]]).T

In [3]:
# sigmoid function
def sig(z):
    return 1 / (1 + np.exp(-z))

In [4]:
# sigmoid function derivation
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [18]:
# considering weights and bias b/w -1 and 1
# no hidden layer weights
weights = 2 * np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
# lr = 0.001 # learning rate 1
# lr = 0.01 # learning rate 2
lr = 0.1 # learning rate 3

In [19]:
for iter in range(10000):
    # Forward propogation without any hidden layer
    output0 = X # output of input layer
    output = sig(np.dot(output0, weights) + bias) # output of output layer
    
    # Backward propogation without any hidden layer
    # Finding the first term = Y_pred - Y_act
    first_term = output - Y

    # Finding the second term = Oj * (1 - Oj)
    input_for_last_layer = np.dot(output0, weights) + bias
    second_term = derivativeSig(input_for_last_layer)

    first_two = first_term * second_term

    # updating the weights
    weights_changes = np.array([[0.0], [0.0]])

    for i in range(2):
        for j in range(4):
            weights_changes[i][0] += first_two[j][0] * output0[j][i]

    weights = weights - lr * weights_changes

    # updating the bias
    bias_change = 0.0
    for j in range(4):
        bias_change += first_two[j][0] * 1

    bias = bias - lr * bias_change

# Ypred values
output = sig(np.dot(X, weights) + bias)

# printing all the values
weights, bias, output

(array([[5.47540089],
        [5.47540088]]),
 array([-8.30581135]),
 array([[2.47015766e-04],
        [5.57028035e-02],
        [5.57028040e-02],
        [9.33701556e-01]]))

For getting better results, play around with learning rate and number of iterations. Thereby, the Y_pred will become much closer to Y_act.