In [1]:
# importing the library
import numpy as np

In [25]:
# creating a numpy array
# Method 1

li = [1, 2, 3]
np.array(li)

# Just in case 
# li = [1, 2, '3']
# np.array(li)
# converts everything into a string

array([1, 2, 3])

In [14]:
# Array full of zeros
a0 = np.zeros(10)
print(a.dtype) # returns type of the data

# Array full of ones
a1 = np.ones(10)

# changing data type is also possible
a1_int = np.ones(10, int)
a1_int

float64


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
# creating 2d arrays
a_2d = np.zeros((2, 3))
print(a_2d)

li_2d = [[1, 2, 3], [4, 5, 6]]
np.array(li_2d)
print(li_2d)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1, 2, 3], [4, 5, 6]]


In [17]:
# changing particular index value
a0[0] = 1
print(a0)

# if we give another data type other than the already applied one, it gets converted into the existing type automatically
a0[0] = "1"
print(a0)

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [36]:
# Accessing elements
print(li[0])

# for 2d arrays
li1_2d = np.array([[11, 12, 13], [14, 15, 16]])
print(li1_2d[0]) # accessing 0th row
print(li1_2d[:, 0]) # accessing 0th column


li2_2d = np.array([[11, 12, 13], [14, 15, 16], [11, 12, 13], [14, 15, 16]])
print(li2_2d[:, 0])
print(li2_2d[0:2, 0])
print(li2_2d[:, 1:3])

1
[11 12 13]
[11 14]
[11 14 11 14]
[11 14]
[[12 13]
 [15 16]
 [12 13]
 [15 16]]


In [22]:
# Slicing
print(li[1:2])

print(li_2d[1:2])

[2]
[[4, 5, 6]]


In [38]:
# Size of the array
print(a0.shape)
print(li1_2d.shape)
print(li2_2d.shape)

(10,)
(2, 3)
(4, 3)
