In [1]:
import numpy as np

In [16]:
a = np.array([1, 2, 3])
b = np.array([5, 6, 7])

In [9]:
# Performs element wise operations

print(a + 2)
print(a * 3)
print(a ** 2)
print(a / 2)
print(a % 2)

print(a + b)
print(a * b)

[3 4 5]
[3 6 9]
[1 4 9]
[0.5 1.  1.5]
[1 0 1]
[ 6  8 10]
[ 5 12 21]


In [11]:
# Built in functions
print(a.mean())
print(b.sum())

2.0
18


In [22]:
# Dot operation
a1_2d = np.array([[1, 2], [3, 4]])
a2_2d = np.array([[10, 20], [30, 40]])

a1_2d.dot(a2_2d)

array([[ 70, 100],
       [150, 220]])

In [17]:
import math as m

In [19]:
# Square distance
dist = ((a - b)**2).sum()
final_ans = m.sqrt(dist)
print(final_ans)

6.928203230275509


In [20]:
# Points to mean distance
x = np.array([1, 3, 5, 6])
dist = ((x - x.mean())**2).sum()
print(dist)

14.75
